### ISSUE TITLE
remote_session_data_helper.jsp (404) not found

### ISSUE THREAD

**Issue by dnwk** [mehmetc/jQuery.PRIMO#1]
I recently found your jQuery code and included in our Primo instance. I found this JS error

"NetworkError: 404 Not Found - http://alliance-primo.hosted.exlibrisgroup.com/primo_library/libweb/remote_session_data_helper.jsp"

**Comment by mehmetc** [comment]
Hi,

Did you copy the contents of scripts/server to the frontend server?
See the readme
file https://github.com/mehmetc/jQuery.PRIMO#a-more-permanent-solution

scp scripts/server/*
primo@my_primo.example.com:/exlibris/primo/p4_1/ng/primo/home/system/tomcat/search/webapps/primo_library?libweb

If you didn't it will still work but the more complicated stuff like
for example view language etc will not. Hope this helps. If you have
any other questions I'll be happy to help.

Mehmet

**Comment by ghost** [comment]
em.... You have FTP access to your Primo server? I am not aware of that.

**Comment by mehmetc** [comment]
Yes we have (for now). It is historical. You need it to copy the JSP files the uploader in the Backend forbids this.
