### ISSUE TITLE
How to retrieve the MARC of a record

### ISSUE THREAD

**Issue by jhercher** [mehmetc/jQuery.PRIMO#13]
Hi,

is there a way to get the original MARC of a record? I see you suggest to uncomment:

```

        <mapping resource="com/exlibris/primo/domain/entities/OriginalSourceRecord.hbm.xml"/>

```

to the hibernate mapping file /exlibris/primo/p4_1/ng/primo/home/system/search/conf/hibernate.cfg.xml 
(I'll definitely need to ask the support for this) 

How do I get the MARC then? Is it even possible to do it like this?

```
    jQuery.PRIMO.records[5].getMARC('xml');
```

Thanks

**Comment by mehmetc** [comment]
Hi Johannes,

I must say that I never had a real need to do anything with the original record in the UI. What are you going to use it for? 
Look at the [librians Workbench](https://github.com/mehmetc/jQuery.PRIMO/blob/master/examples/librariansWB.html) example it contains code on how to do it.

You need to call the API directly like:

> /primo_library/libweb/jqp/record/{{ recordId }}.xml

If the hibernate mapping is enabled you will get the original xml file else it will return the pnx record.

Hope this answers your question.

Mehmet

**Comment by jhercher** [comment]
Hi Mehmet,
thanks for your quick response. I found a way without touching `hibernate.cfg.xml` by using the ALMA API: 

```
    https://api-eu.hosted.exlibrisgroup.com/almaws/v1/bibs/{{mmsId}}?apiKey=xxxx

```

Having a quick look into the published MARC is often useful to debug normalization rules in Primo. Using the API call above you won't need to login to ALMA, i.e. you save a bunch of clicks and copy'n paste ;) 

Cheers,
Johannes
