### ISSUE TITLE
$.PRIMO.session.user.isLoggedIn() in IE11

### ISSUE THREAD

**Issue by dnwk** [mehmetc/jQuery.PRIMO#2]
It is a wired issue in IE. $.PRIMO.session.user.isLoggedIn()  return false even after use login. But one I click refresh on browser, it return true

**Comment by dnwk** [comment]
But once I click refresh on browser, it return true(after login)

I test it in IE11

**Comment by mehmetc** [comment]
Can I get the URL to the view?

**Comment by dnwk** [comment]
sherlock.whitman.edu

Currently, I will give a popup box when user is not login.  I put a workaround code in it so that in IE after login, it does a location.reload.

**Comment by mehmetc** [comment]
I have restructured a bit.  Can you try the latest release? I also noticed that you are loading the library in the header. It would be better to load it in the footer.

**Comment by dnwk** [comment]
I add an $.PRIMO.reload();  It does not make any differences. I am not sure if I am using the reload correctly.

**Comment by mehmetc** [comment]
The problem is that you are loading the library in the header instead of the footer. Could you move your code to the footer? If you have time we can experiment with document.ready etc.

**Comment by dnwk** [comment]
I try to put it in footer but same old problem in IE

**Comment by dnwk** [comment]
http://alliance-primo-sb.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?vid=WHITC_POC

**Comment by mehmetc** [comment]
Maybe we should do a Lync, WebEx, Hangout or something like that. I am unable to reproduce.

**Comment by dnwk** [comment]
Sent you an email.
